//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Personel_TotalAsistan
    {
        public int ID { get; set; }
        public string TCkNo { get; set; }
        public string SicilNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string AnadalAdi { get; set; }
        public System.DateTime BaslangicTarih { get; set; }
        public System.DateTime BitisTarih { get; set; }
        public Nullable<System.DateTime> TezVerilmeTarih { get; set; }
        public Nullable<System.DateTime> TezBitisTarih { get; set; }
        public string OgrtmTCkNo { get; set; }
        public string OgrtmAd { get; set; }
        public string OgrtmSoyad { get; set; }
        public string Unvanı { get; set; }
        public string BabaAdi { get; set; }
        public string AnaAdi { get; set; }
        public string Dogumyeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> AyrilisTarihi { get; set; }
        public string GittigiYer { get; set; }
        public bool MezuniyetDurumu { get; set; }
        public Nullable<System.DateTime> MezuniyetTarihi { get; set; }
        public string MezunOlFakulte { get; set; }
        public string AskerlikSube { get; set; }
        public Nullable<System.DateTime> SevkTehirTarihi { get; set; }
        public Nullable<System.DateTime> SonSevkThrTarihi { get; set; }
        public string TUSDonemi { get; set; }
        public Nullable<decimal> TusNotu { get; set; }
        public string TescilNo { get; set; }
        public string DiplomaNo { get; set; }
        public string KayitTuru { get; set; }
        public Nullable<decimal> YabanciDilPuan { get; set; }
        public string TezAdi { get; set; }
        public Nullable<int> Sure_gun { get; set; }
        public bool TezKabul { get; set; }
        public Nullable<int> Egitim_yili { get; set; }
        public int Sure_yil { get; set; }
        public bool Pasif { get; set; }
    }
}
